node {
    stage '初期設定'
    def jobname = 'test'

    stage 'ブランチ最新化'
    sh "cd ../${jobname}@script && git pull origin master"

    stage 'デプロイ実行'
    sh "whoami"
    sh "cd ../${jobname}@script/jenkins/capistrano && cap production deploy"

    stage '終了作業・GITクリア'
    sh "cd ../${jobname}@script && git clean -fdx"

    echo "finish"
}
